directories:
  'app/controllers':
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    UncommunicativeModuleName:
      accept:
        - V1
  'app/helpers':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false
  'app/models':
    InstanceVariableAssumption:
      enabled: false
  'app/serializers':
    IrresponsibleModule:
      enabled: false

exclude_paths:
  - db/migrate
