plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - AllowedNames
AllCops:
  NewCops: enable
  Include:
    - app/**/*.rb
    - bin/setup
    - config/**/*.rb
    - spec/**/*.rb
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/**/*.rb
    - node_modules/**/*
    - spec/spec_helper.rb
    - test/test_helper.rb
    - tmp/**/*
    - vendor/**/*

Bundler/GemVersion:
  Enabled: true

# Layout/ClassStructure:
#   Enabled: true

Layout/EndOfLine:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  Severity: warning

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  IgnoreCopDirectives: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

# Make sure to include spaces in any percent literal expressions
# e.g., %s{ a s d f }, not %s{a s d f}
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

# Metrics/AbcSize:
#   Max: 25

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - 'Gemfile'

Naming/InclusiveLanguage:
  Enabled: true

Naming/MethodParameterName:
  AllowedNames:
    - qc

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/mailers/**/*
    - config/**/*

Style/MixinUsage:
  Exclude:
    - bin/*

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Rails/UnknownEnv:
  Environments:
    - 'cypress'
    - 'development'
    - 'production'
    - 'test'

RSpec/ExampleLength:
  Max: 15

Style/RequireOrder:
  Enabled: true
