require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Include:
    - app/**/*.rb
    - spec/**/*.rb
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/**/*.rb
    - node_modules/**/*
    - spec/spec_helper.rb
    - test/test_helper.rb
    - vendor/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  Severity: warning

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  IgnoreCopDirectives: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

# Make sure to include spaces in any percent literal expressions
# e.g., %s{ a s d f }, not %s{a s d f}
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/mailers/**/*
    - config/**/*

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

RSpec/ExampleLength:
  Max: 15
