approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-disable-typescript-compat.cjs
    spec: "plugin-disable-typescript-compat"
    