version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password

  # main rails blob
  ruby:
    build: .
    command: bundle exec rails s --pid /tmp/server.pid -b 0.0.0.0 -p 3000
    depends_on:
      - postgres
      - webpack
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres
    stdin_open: true
    tty: true

  # Runs the webpack dev server
  webpack:
    build: .
    volumes:
      - .:/myapp
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035

# Make a volume, because windows screws up the the permissions
# so postgres has a fit.
volumes:
  postgres:
    driver: local
