// flow-typed signature: 69f5cd30484b31f359003d4ea873975d
// flow-typed version: <<STUB>>/inline-style-prefixer_v^5.0.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-style-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-style-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inline-style-prefixer/es/createPrefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/data' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/generator/generatePluginList' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/generator/generatePrefixMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/generator/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/generator/maps/pluginMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/generator/maps/propertyMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/backgroundClip' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/crossFade' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/cursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/filter' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/imageSet' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/utils/addNewValuesOnly' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/utils/capitalizeString' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/utils/isObject' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/utils/prefixProperty' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/es/utils/prefixValue' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/createPrefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/data' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/generator/generatePluginList' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/generator/generatePrefixMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/generator/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/generator/maps/pluginMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/generator/maps/propertyMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/backgroundClip' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/crossFade' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/cursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/filter' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/imageSet' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/addNewValuesOnly' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/capitalizeString' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/isObject' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/prefixProperty' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/prefixValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inline-style-prefixer/es/createPrefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/createPrefixer'>;
}
declare module 'inline-style-prefixer/es/data.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/data'>;
}
declare module 'inline-style-prefixer/es/generator/generatePluginList.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/generator/generatePluginList'>;
}
declare module 'inline-style-prefixer/es/generator/generatePrefixMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/generator/generatePrefixMap'>;
}
declare module 'inline-style-prefixer/es/generator/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/generator/index'>;
}
declare module 'inline-style-prefixer/es/generator/maps/pluginMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/generator/maps/pluginMap'>;
}
declare module 'inline-style-prefixer/es/generator/maps/propertyMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/generator/maps/propertyMap'>;
}
declare module 'inline-style-prefixer/es/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/index'>;
}
declare module 'inline-style-prefixer/es/plugins/backgroundClip.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/backgroundClip'>;
}
declare module 'inline-style-prefixer/es/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/calc'>;
}
declare module 'inline-style-prefixer/es/plugins/crossFade.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/crossFade'>;
}
declare module 'inline-style-prefixer/es/plugins/cursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/cursor'>;
}
declare module 'inline-style-prefixer/es/plugins/filter.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/filter'>;
}
declare module 'inline-style-prefixer/es/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/flex'>;
}
declare module 'inline-style-prefixer/es/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/es/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/es/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/gradient'>;
}
declare module 'inline-style-prefixer/es/plugins/imageSet.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/imageSet'>;
}
declare module 'inline-style-prefixer/es/plugins/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/index'>;
}
declare module 'inline-style-prefixer/es/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/position'>;
}
declare module 'inline-style-prefixer/es/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/sizing'>;
}
declare module 'inline-style-prefixer/es/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/plugins/transition'>;
}
declare module 'inline-style-prefixer/es/utils/addNewValuesOnly.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/utils/addNewValuesOnly'>;
}
declare module 'inline-style-prefixer/es/utils/capitalizeString.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/utils/capitalizeString'>;
}
declare module 'inline-style-prefixer/es/utils/isObject.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/utils/isObject'>;
}
declare module 'inline-style-prefixer/es/utils/prefixProperty.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/utils/prefixProperty'>;
}
declare module 'inline-style-prefixer/es/utils/prefixValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/es/utils/prefixValue'>;
}
declare module 'inline-style-prefixer/lib/createPrefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/createPrefixer'>;
}
declare module 'inline-style-prefixer/lib/data.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/data'>;
}
declare module 'inline-style-prefixer/lib/generator/generatePluginList.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/generator/generatePluginList'>;
}
declare module 'inline-style-prefixer/lib/generator/generatePrefixMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/generator/generatePrefixMap'>;
}
declare module 'inline-style-prefixer/lib/generator/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/generator/index'>;
}
declare module 'inline-style-prefixer/lib/generator/maps/pluginMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/generator/maps/pluginMap'>;
}
declare module 'inline-style-prefixer/lib/generator/maps/propertyMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/generator/maps/propertyMap'>;
}
declare module 'inline-style-prefixer/lib/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/index'>;
}
declare module 'inline-style-prefixer/lib/plugins/backgroundClip.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/backgroundClip'>;
}
declare module 'inline-style-prefixer/lib/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/calc'>;
}
declare module 'inline-style-prefixer/lib/plugins/crossFade.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/crossFade'>;
}
declare module 'inline-style-prefixer/lib/plugins/cursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/cursor'>;
}
declare module 'inline-style-prefixer/lib/plugins/filter.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/filter'>;
}
declare module 'inline-style-prefixer/lib/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flex'>;
}
declare module 'inline-style-prefixer/lib/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/lib/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/lib/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/gradient'>;
}
declare module 'inline-style-prefixer/lib/plugins/imageSet.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/imageSet'>;
}
declare module 'inline-style-prefixer/lib/plugins/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/index'>;
}
declare module 'inline-style-prefixer/lib/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/position'>;
}
declare module 'inline-style-prefixer/lib/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/sizing'>;
}
declare module 'inline-style-prefixer/lib/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/transition'>;
}
declare module 'inline-style-prefixer/lib/utils/addNewValuesOnly.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/addNewValuesOnly'>;
}
declare module 'inline-style-prefixer/lib/utils/capitalizeString.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/capitalizeString'>;
}
declare module 'inline-style-prefixer/lib/utils/isObject.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/isObject'>;
}
declare module 'inline-style-prefixer/lib/utils/prefixProperty.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/prefixProperty'>;
}
declare module 'inline-style-prefixer/lib/utils/prefixValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/prefixValue'>;
}
