// flow-typed signature: f562af8ca3ea9f45511856c3998fdb4a
// flow-typed version: <<STUB>>/mock-local-storage_v^1.0.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-local-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-local-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-local-storage/lib/mock-localstorage' {
  declare module.exports: any;
}

declare module 'mock-local-storage/test/mock-localstorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-local-storage/lib/mock-localstorage.js' {
  declare module.exports: $Exports<'mock-local-storage/lib/mock-localstorage'>;
}
declare module 'mock-local-storage/test/mock-localstorage.js' {
  declare module.exports: $Exports<'mock-local-storage/test/mock-localstorage'>;
}
