// flow-typed signature: 0911ea5be6440603193878adb4e3bfd5
// flow-typed version: <<STUB>>/path-complete-extname_v^1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-complete-extname'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-complete-extname' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-complete-extname/Gruntfile' {
  declare module.exports: any;
}

declare module 'path-complete-extname/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-complete-extname/Gruntfile.js' {
  declare module.exports: $Exports<'path-complete-extname/Gruntfile'>;
}
declare module 'path-complete-extname/index' {
  declare module.exports: $Exports<'path-complete-extname'>;
}
declare module 'path-complete-extname/index.js' {
  declare module.exports: $Exports<'path-complete-extname'>;
}
declare module 'path-complete-extname/test.js' {
  declare module.exports: $Exports<'path-complete-extname/test'>;
}
