// flow-typed signature: b2d9d56f6d464a2402ee8087e299f9b1
// flow-typed version: <<STUB>>/rails-erb-loader_v^5.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rails-erb-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rails-erb-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rails-erb-loader/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rails-erb-loader/index' {
  declare module.exports: $Exports<'rails-erb-loader'>;
}
declare module 'rails-erb-loader/index.js' {
  declare module.exports: $Exports<'rails-erb-loader'>;
}
declare module 'rails-erb-loader/test.js' {
  declare module.exports: $Exports<'rails-erb-loader/test'>;
}
