// flow-typed signature: d1f415a50f0184be0c3a0ef48c985471
// flow-typed version: <<STUB>>/react-markdown_v^3.3.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown/lib/ast-to-react' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/get-definitions' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/disallow-node' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/naive-html' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/renderers' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/uriTransformer' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/wrap-table-rows' {
  declare module.exports: any;
}

declare module 'react-markdown/umd/react-markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown/lib/ast-to-react.js' {
  declare module.exports: $Exports<'react-markdown/lib/ast-to-react'>;
}
declare module 'react-markdown/lib/get-definitions.js' {
  declare module.exports: $Exports<'react-markdown/lib/get-definitions'>;
}
declare module 'react-markdown/lib/plugins/disallow-node.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/disallow-node'>;
}
declare module 'react-markdown/lib/plugins/naive-html.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/naive-html'>;
}
declare module 'react-markdown/lib/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/lib/react-markdown'>;
}
declare module 'react-markdown/lib/renderers.js' {
  declare module.exports: $Exports<'react-markdown/lib/renderers'>;
}
declare module 'react-markdown/lib/uriTransformer.js' {
  declare module.exports: $Exports<'react-markdown/lib/uriTransformer'>;
}
declare module 'react-markdown/lib/wrap-table-rows.js' {
  declare module.exports: $Exports<'react-markdown/lib/wrap-table-rows'>;
}
declare module 'react-markdown/umd/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/umd/react-markdown'>;
}
