// flow-typed signature: 561359d5009e7ac1367b7309cd31a611
// flow-typed version: <<STUB>>/redux-optimistic-ui_v^3.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-optimistic-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-optimistic-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-optimistic-ui/dist/redux-optimistic-ui' {
  declare module.exports: any;
}

declare module 'redux-optimistic-ui/dist/redux-optimistic-ui.min' {
  declare module.exports: any;
}

declare module 'redux-optimistic-ui/lib/array-utils' {
  declare module.exports: any;
}

declare module 'redux-optimistic-ui/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-optimistic-ui/dist/redux-optimistic-ui.js' {
  declare module.exports: $Exports<'redux-optimistic-ui/dist/redux-optimistic-ui'>;
}
declare module 'redux-optimistic-ui/dist/redux-optimistic-ui.min.js' {
  declare module.exports: $Exports<'redux-optimistic-ui/dist/redux-optimistic-ui.min'>;
}
declare module 'redux-optimistic-ui/lib/array-utils.js' {
  declare module.exports: $Exports<'redux-optimistic-ui/lib/array-utils'>;
}
declare module 'redux-optimistic-ui/lib/index.js' {
  declare module.exports: $Exports<'redux-optimistic-ui/lib/index'>;
}
