// flow-typed signature: 77242fe294cfd10ec09aad8295369d52
// flow-typed version: <<STUB>>/scroll-to-element_v^2.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-to-element'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-to-element' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-to-element/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-to-element/example.js' {
  declare module.exports: $Exports<'scroll-to-element/example'>;
}
declare module 'scroll-to-element/index' {
  declare module.exports: $Exports<'scroll-to-element'>;
}
declare module 'scroll-to-element/index.js' {
  declare module.exports: $Exports<'scroll-to-element'>;
}
