// flow-typed signature: 2ea8fea40bf72f5043762ad6b1be8e9a
// flow-typed version: <<STUB>>/typeface-roboto_v^0.0.54/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
