// flow-typed signature: baae91a2f0a34f2a315e929d970e39e8
// flow-typed version: <<STUB>>/@babel/plugin-proposal-function-sent_v^7.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-function-sent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-function-sent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-function-sent/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-function-sent/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-function-sent/lib/index'>;
}
