export const TOGGLE_MENU = 'TOGGLE_MENU'

export const REQUEST_CHAR = 'REQUEST_CHAR'
export const RECEIVE_CHAR = 'RECEIVE_CHAR'
export const REQUEST_CHRONICLE = 'REQUEST_CHRONICLE'
export const RECEIVE_CHRONICLE = 'RECEIVE_CHRONICLE'

export const UPDATE_CHAR = 'UPDATE_CHAR'
export const UPDATE_CHAR_COMPLETE = 'UPDATE_CHAR_COMPLETE'
export const CREATE_CHAR = 'CREATE_CHAR'
export const CREATE_CHAR_COMPLETE = 'CREATE_CHAR_COMPLETE'

export const UPDATE_WEAP = 'UPDATE_WEAP'
export const UPDATE_WEAP_COMPLETE = 'UPDATE_WEAP_COMPLETE'
export const CREATE_WEAP = 'CREATE_WEAP'
export const CREATE_WEAP_COMPLETE = 'CREATE_WEAP_COMPLETE'

export const UPDATE_MERIT = 'UPDATE_MERIT'
export const UPDATE_MERIT_COMPLETE = 'UPDATE_MERIT_COMPLETE'
export const CREATE_MERIT = 'CREATE_MERIT'
export const CREATE_MERIT_COMPLETE = 'CREATE_MERIT_COMPLETE'

export const UPDATE_QC = 'UPDATE_QC'
export const UPDATE_QC_COMPLETE = 'UPDATE_QC_COMPLETE'
export const CREATE_QC = 'CREATE_QC'
export const CREATE_QC_COMPLETE = 'CREATE_QC_COMPLETE'

export const UPDATE_QC_MERIT = 'UPDATE_QC_MERIT'
export const UPDATE_QC_MERIT_COMPLETE = 'UPDATE_QC_MERIT_COMPLETE'
export const CREATE_QC_MERIT = 'CREATE_QC_MERIT'
export const CREATE_QC_MERIT_COMPLETE = 'CREATE_QC_MERIT_COMPLETE'

export const UPDATE_QC_ACTION = 'UPDATE_QC_ACTION'
export const UPDATE_QC_ACTION_COMPLETE = 'UPDATE_QC_ACTION_COMPLETE'
export const CREATE_QC_ACTION = 'CREATE_QC_ACTION'
export const CREATE_QC_ACTION_COMPLETE = 'CREATE_QC_ACTION_COMPLETE'
