import type { Battlegroup, QcAttack } from './types'
import { ex3ReleaseDate } from '@/testUtils'

export const mockBattlegroup: Battlegroup = {
  name: 'Mock Battlegroup',
  description: '',
  magnitude: 0,
  size: 0,
  might: 0,
  drill: 0,
  soak: 0,
  health_levels: 0,
  perfect_morale: false,
  essence: 0,
  willpower_temporary: 0,
  willpower_permanent: 0,
  movement: 0,
  senses: 0,
  armor_name: '',
  hardness: 0,
  join_battle: 0,
  evasion: 0,
  parry: 0,
  guile: 0,
  resolve: 0,
  appearance: 0,
  portrait_link: '',
  qc_attacks: [],
  type: 'battlegroup',
  player_id: 0,
  chronicle_id: 0,
  public: false,
  pinned: false,
  hidden: false,
  editable: false,
  deletable: false,
  id: 0,
  created_at: ex3ReleaseDate,
  updated_at: ex3ReleaseDate,
  chronicle_sorting: 0,
  sorting: 0,
  initiative: 0,
  onslaught: 0,
  in_combat: false,
  has_acted: false,
}

export const mockAttack: QcAttack = {
  name: 'Mock Attack',
  pool: 0,
  range: 'medium',
  damage: 0,
  overwhelming: 0,
  tags: [],
  qc_attackable_type: 'Qc',
  qc_attackable_id: 0,
  sorting: 0,
  id: 0,
  created_at: ex3ReleaseDate,
  updated_at: ex3ReleaseDate,
}
