name: 'Ruby on Rails CI'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      CI: true
      RAILS_ENV: test
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/ci
